language: csharp
solution: InsertIt.sln
install:
  - nuget restore InsertIt.sln
  - nuget install xunit.runner.console -Version 2.1.0 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release InsertIt.sln
  - mono ./testrunner/xunit.runner.console.2.1.0/tools/xunit.console.exe ./tests/InsertIt.Tests/bin/Release/InsertIt.Tests.dll
