language: csharp
solution: InsertIt.sln
install:
  - nuget restore InsertIt.sln
  - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release InsertIt.sln
  - mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ./tests/InsertIt.Tests/bin/Release/InsertIt.Tests.dll
